---
engines:
  eslint-8:
    enabled: true
    config-file: eslint.config.mjs
  prettier:
    enabled: false
  duplication:
    enabled: true
    exclude_paths:
      - "**.spec.ts"
  markdownlint:
    enabled: true
    config:
      default:
        MD013: false
